### ISSUE TITLE
format for multiple request identifiers is not browser friendly

### ISSUE THREAD

**Issue by shiphrah** [gbv/daia#18]
multiple request identifiers are specified to be separated by a vertical bar (| i. e. %7C).

If I am not mistaken, the vertical bar may not be part of a query string unescaped (cf. RFC3986). This makes it a bit cumbersome to test with the browser.

Can we find an alternative or additional separator?

**Comment by shiphrah** [comment]
But this means that the DAIA-Specifaction requires that a DAIA-Server MUST explicitly violate RFC 3986. Is this really a good choice? What about a different separator? I think I could live with a SHOULD.

**Comment by nichtich** [comment]
ok, will be included in 0.9.6.
