### ISSUE TITLE
Limit openaccess to digital resources

### ISSUE THREAD

**Issue by nichtich** [gbv/daia#19]
An openaccess service should provide a direct link to the document in field `href`without paywall, IP-restrictions, login etc.

An alternative might be a boolean flag to indicate the type of publication (digital/physical, see #20).

**Comment by lahmann** [comment]
I agree, the service `openaccess` should be only assigned to items that are available without any copyright or physical restrictions, which only applies to digital documents published under a open access license (e.g. CC-BY). Even printed versions of a work published under CC-BY would be restraint by the property rights of the library holding this printed version.
Therefore I suggest to explicitly mention these relations in the definition of DAIA services in the specification:

```
Each service has a service type to define what can be done with a given item. This is constrained by the license under which the item is usable and the type of the item (digital/physical). DAIA defines the following service types
```

**Comment by nichtich** [comment]
Version 0.9.6 included a more detailed specification of service type `open access` and recommendations to specify an Open Access license.

**Comment by lahmann** [comment]
Great, thanks!
