### ISSUE TITLE
How to model document availability vs. item availability

### ISSUE THREAD

**Issue by lahmann** [gbv/daia#30]
Some ILS do not offer holding information for items but only availability information for the whole document (in terms of can any item for this document be loaned or not). The DAIA document is not specified to contain any availability information, modeling the above mentioned availability with a (virtual) item would not be correct semantically.
Is there a way to model such document availability with DAIA?

**Comment by nichtich** [comment]
What's wrong with having a dummy item that represents any available item? The only problem might be the item identifier if it needs to be reused in other applications but items don't need to have an id anyway.

**Comment by nichtich** [comment]
The solution is a dummy item. Whether an item is such a dummy is only of internal interest so it is not semantically wrong outside of the library system. If such item is requested via PAIA, PAIA supports mapping a "dummy" item ID (field `requested`) to a more stable ID.
